---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 1024

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: documentation

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04-nochef
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[ruby_compile::default]
    attributes:
